site_name: Saf‑t Accounting User Guide
site_url: https://teodorval.github.io/saftviewer-docs

# КАЗВАМЕ НА MATERIAL, ЧЕ САЙТЪТ Е В ПОДДИРЕКТОРИЯ
extra:
  base_url: /saftviewer-docs/

theme:
  name: material
  language: bg
  palette:
    - scheme: default
      primary: indigo
      accent: blue
    - scheme: slate
      primary: indigo
      accent: blue
  features:
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link

# JS файловете вече ще се изпълняват правилно
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/medium-zoom/1.0.6/medium-zoom.min.js
  - js/image-zoom.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.extra

nav:
  - Въведение: index.md
  - Избор на фирма: firm-selection.md
  - Главен екран: main-window.md

  - Модули:
      - Осчетоводяване: accounting.md
      - Приходни документи: incoming-documents.md
      - Разходни документи: outgoing-documents.md
      - Плащания: payments.md
      - Активи: assets.md
      - Складови операции: warehouse.md
      - Справки: reports.md
      - Данни за фирмата: company-data.md
      - Сметкоплан: chart-of-accounts.md
      - Клиенти: clients.md
      - Доставчици: suppliers.md
      - Продукти: products.md
      - Импорт / Експорт: import-export.md

  - Екрани:
      - Редакция на сметка: account-edit.md
      - Редакция на клиент: client-edit.md
      - Редакция на доставчик: supplier-edit.md
      - Редакция на стока: product-edit.md
      - Редакция на приходни документи: incoming-edit.md
      - Редакция на разходни документи: outgoing-edit.md
      - Редакция на плащане: payment-edit.md
      - Редакция на актив: asset-edit.md
      - Редакция на складова операция: warehouse-edit.md

  - Troubleshooting: troubleshooting.md
  - Release Notes: release-notes.md
  - Екрани: screenshots.md
